// Code generated by go-mockgen 1.1.2; DO NOT EDIT.

package sqlbuilder

import (
	"sync"

	adapter "unknwon.dev/norm/adapter"
)

// MockAdapter is a mock implementation of the Adapter interface (from the
// package unknwon.dev/norm/adapter) used for unit testing.
type MockAdapter struct {
	// ExecutorFunc is an instance of a mock function object controlling the
	// behavior of the method Executor.
	ExecutorFunc *AdapterExecutorFunc
	// FormatSQLFunc is an instance of a mock function object controlling
	// the behavior of the method FormatSQL.
	FormatSQLFunc *AdapterFormatSQLFunc
	// NameFunc is an instance of a mock function object controlling the
	// behavior of the method Name.
	NameFunc *AdapterNameFunc
	// TyperFunc is an instance of a mock function object controlling the
	// behavior of the method Typer.
	TyperFunc *AdapterTyperFunc
}

// NewMockAdapter creates a new mock of the Adapter interface. All methods
// return zero values for all results, unless overwritten.
func NewMockAdapter() *MockAdapter {
	return &MockAdapter{
		ExecutorFunc: &AdapterExecutorFunc{
			defaultHook: func() adapter.Executor {
				return nil
			},
		},
		FormatSQLFunc: &AdapterFormatSQLFunc{
			defaultHook: func(string) string {
				return ""
			},
		},
		NameFunc: &AdapterNameFunc{
			defaultHook: func() adapter.Name {
				return ""
			},
		},
		TyperFunc: &AdapterTyperFunc{
			defaultHook: func() adapter.Typer {
				return nil
			},
		},
	}
}

// NewStrictMockAdapter creates a new mock of the Adapter interface. All
// methods panic on invocation, unless overwritten.
func NewStrictMockAdapter() *MockAdapter {
	return &MockAdapter{
		ExecutorFunc: &AdapterExecutorFunc{
			defaultHook: func() adapter.Executor {
				panic("unexpected invocation of MockAdapter.Executor")
			},
		},
		FormatSQLFunc: &AdapterFormatSQLFunc{
			defaultHook: func(string) string {
				panic("unexpected invocation of MockAdapter.FormatSQL")
			},
		},
		NameFunc: &AdapterNameFunc{
			defaultHook: func() adapter.Name {
				panic("unexpected invocation of MockAdapter.Name")
			},
		},
		TyperFunc: &AdapterTyperFunc{
			defaultHook: func() adapter.Typer {
				panic("unexpected invocation of MockAdapter.Typer")
			},
		},
	}
}

// NewMockAdapterFrom creates a new mock of the MockAdapter interface. All
// methods delegate to the given implementation, unless overwritten.
func NewMockAdapterFrom(i adapter.Adapter) *MockAdapter {
	return &MockAdapter{
		ExecutorFunc: &AdapterExecutorFunc{
			defaultHook: i.Executor,
		},
		FormatSQLFunc: &AdapterFormatSQLFunc{
			defaultHook: i.FormatSQL,
		},
		NameFunc: &AdapterNameFunc{
			defaultHook: i.Name,
		},
		TyperFunc: &AdapterTyperFunc{
			defaultHook: i.Typer,
		},
	}
}

// AdapterExecutorFunc describes the behavior when the Executor method of
// the parent MockAdapter instance is invoked.
type AdapterExecutorFunc struct {
	defaultHook func() adapter.Executor
	hooks       []func() adapter.Executor
	history     []AdapterExecutorFuncCall
	mutex       sync.Mutex
}

// Executor delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockAdapter) Executor() adapter.Executor {
	r0 := m.ExecutorFunc.nextHook()()
	m.ExecutorFunc.appendCall(AdapterExecutorFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the Executor method of
// the parent MockAdapter instance is invoked and the hook queue is empty.
func (f *AdapterExecutorFunc) SetDefaultHook(hook func() adapter.Executor) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Executor method of the parent MockAdapter instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *AdapterExecutorFunc) PushHook(hook func() adapter.Executor) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *AdapterExecutorFunc) SetDefaultReturn(r0 adapter.Executor) {
	f.SetDefaultHook(func() adapter.Executor {
		return r0
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *AdapterExecutorFunc) PushReturn(r0 adapter.Executor) {
	f.PushHook(func() adapter.Executor {
		return r0
	})
}

func (f *AdapterExecutorFunc) nextHook() func() adapter.Executor {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *AdapterExecutorFunc) appendCall(r0 AdapterExecutorFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of AdapterExecutorFuncCall objects describing
// the invocations of this function.
func (f *AdapterExecutorFunc) History() []AdapterExecutorFuncCall {
	f.mutex.Lock()
	history := make([]AdapterExecutorFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// AdapterExecutorFuncCall is an object that describes an invocation of
// method Executor on an instance of MockAdapter.
type AdapterExecutorFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 adapter.Executor
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c AdapterExecutorFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c AdapterExecutorFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// AdapterFormatSQLFunc describes the behavior when the FormatSQL method of
// the parent MockAdapter instance is invoked.
type AdapterFormatSQLFunc struct {
	defaultHook func(string) string
	hooks       []func(string) string
	history     []AdapterFormatSQLFuncCall
	mutex       sync.Mutex
}

// FormatSQL delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockAdapter) FormatSQL(v0 string) string {
	r0 := m.FormatSQLFunc.nextHook()(v0)
	m.FormatSQLFunc.appendCall(AdapterFormatSQLFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the FormatSQL method of
// the parent MockAdapter instance is invoked and the hook queue is empty.
func (f *AdapterFormatSQLFunc) SetDefaultHook(hook func(string) string) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// FormatSQL method of the parent MockAdapter instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *AdapterFormatSQLFunc) PushHook(hook func(string) string) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *AdapterFormatSQLFunc) SetDefaultReturn(r0 string) {
	f.SetDefaultHook(func(string) string {
		return r0
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *AdapterFormatSQLFunc) PushReturn(r0 string) {
	f.PushHook(func(string) string {
		return r0
	})
}

func (f *AdapterFormatSQLFunc) nextHook() func(string) string {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *AdapterFormatSQLFunc) appendCall(r0 AdapterFormatSQLFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of AdapterFormatSQLFuncCall objects describing
// the invocations of this function.
func (f *AdapterFormatSQLFunc) History() []AdapterFormatSQLFuncCall {
	f.mutex.Lock()
	history := make([]AdapterFormatSQLFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// AdapterFormatSQLFuncCall is an object that describes an invocation of
// method FormatSQL on an instance of MockAdapter.
type AdapterFormatSQLFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 string
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c AdapterFormatSQLFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c AdapterFormatSQLFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// AdapterNameFunc describes the behavior when the Name method of the parent
// MockAdapter instance is invoked.
type AdapterNameFunc struct {
	defaultHook func() adapter.Name
	hooks       []func() adapter.Name
	history     []AdapterNameFuncCall
	mutex       sync.Mutex
}

// Name delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockAdapter) Name() adapter.Name {
	r0 := m.NameFunc.nextHook()()
	m.NameFunc.appendCall(AdapterNameFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the Name method of the
// parent MockAdapter instance is invoked and the hook queue is empty.
func (f *AdapterNameFunc) SetDefaultHook(hook func() adapter.Name) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Name method of the parent MockAdapter instance invokes the hook at the
// front of the queue and discards it. After the queue is empty, the default
// hook function is invoked for any future action.
func (f *AdapterNameFunc) PushHook(hook func() adapter.Name) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *AdapterNameFunc) SetDefaultReturn(r0 adapter.Name) {
	f.SetDefaultHook(func() adapter.Name {
		return r0
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *AdapterNameFunc) PushReturn(r0 adapter.Name) {
	f.PushHook(func() adapter.Name {
		return r0
	})
}

func (f *AdapterNameFunc) nextHook() func() adapter.Name {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *AdapterNameFunc) appendCall(r0 AdapterNameFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of AdapterNameFuncCall objects describing the
// invocations of this function.
func (f *AdapterNameFunc) History() []AdapterNameFuncCall {
	f.mutex.Lock()
	history := make([]AdapterNameFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// AdapterNameFuncCall is an object that describes an invocation of method
// Name on an instance of MockAdapter.
type AdapterNameFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 adapter.Name
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c AdapterNameFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c AdapterNameFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// AdapterTyperFunc describes the behavior when the Typer method of the
// parent MockAdapter instance is invoked.
type AdapterTyperFunc struct {
	defaultHook func() adapter.Typer
	hooks       []func() adapter.Typer
	history     []AdapterTyperFuncCall
	mutex       sync.Mutex
}

// Typer delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockAdapter) Typer() adapter.Typer {
	r0 := m.TyperFunc.nextHook()()
	m.TyperFunc.appendCall(AdapterTyperFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the Typer method of the
// parent MockAdapter instance is invoked and the hook queue is empty.
func (f *AdapterTyperFunc) SetDefaultHook(hook func() adapter.Typer) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Typer method of the parent MockAdapter instance invokes the hook at the
// front of the queue and discards it. After the queue is empty, the default
// hook function is invoked for any future action.
func (f *AdapterTyperFunc) PushHook(hook func() adapter.Typer) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *AdapterTyperFunc) SetDefaultReturn(r0 adapter.Typer) {
	f.SetDefaultHook(func() adapter.Typer {
		return r0
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *AdapterTyperFunc) PushReturn(r0 adapter.Typer) {
	f.PushHook(func() adapter.Typer {
		return r0
	})
}

func (f *AdapterTyperFunc) nextHook() func() adapter.Typer {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *AdapterTyperFunc) appendCall(r0 AdapterTyperFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of AdapterTyperFuncCall objects describing the
// invocations of this function.
func (f *AdapterTyperFunc) History() []AdapterTyperFuncCall {
	f.mutex.Lock()
	history := make([]AdapterTyperFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// AdapterTyperFuncCall is an object that describes an invocation of method
// Typer on an instance of MockAdapter.
type AdapterTyperFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 adapter.Typer
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c AdapterTyperFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c AdapterTyperFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// MockTyper is a mock implementation of the Typer interface (from the
// package unknwon.dev/norm/adapter) used for unit testing.
type MockTyper struct {
	// ScannerFunc is an instance of a mock function object controlling the
	// behavior of the method Scanner.
	ScannerFunc *TyperScannerFunc
	// ValuerFunc is an instance of a mock function object controlling the
	// behavior of the method Valuer.
	ValuerFunc *TyperValuerFunc
}

// NewMockTyper creates a new mock of the Typer interface. All methods
// return zero values for all results, unless overwritten.
func NewMockTyper() *MockTyper {
	return &MockTyper{
		ScannerFunc: &TyperScannerFunc{
			defaultHook: func(interface{}) interface{} {
				return nil
			},
		},
		ValuerFunc: &TyperValuerFunc{
			defaultHook: func(interface{}) interface{} {
				return nil
			},
		},
	}
}

// NewStrictMockTyper creates a new mock of the Typer interface. All methods
// panic on invocation, unless overwritten.
func NewStrictMockTyper() *MockTyper {
	return &MockTyper{
		ScannerFunc: &TyperScannerFunc{
			defaultHook: func(interface{}) interface{} {
				panic("unexpected invocation of MockTyper.Scanner")
			},
		},
		ValuerFunc: &TyperValuerFunc{
			defaultHook: func(interface{}) interface{} {
				panic("unexpected invocation of MockTyper.Valuer")
			},
		},
	}
}

// NewMockTyperFrom creates a new mock of the MockTyper interface. All
// methods delegate to the given implementation, unless overwritten.
func NewMockTyperFrom(i adapter.Typer) *MockTyper {
	return &MockTyper{
		ScannerFunc: &TyperScannerFunc{
			defaultHook: i.Scanner,
		},
		ValuerFunc: &TyperValuerFunc{
			defaultHook: i.Valuer,
		},
	}
}

// TyperScannerFunc describes the behavior when the Scanner method of the
// parent MockTyper instance is invoked.
type TyperScannerFunc struct {
	defaultHook func(interface{}) interface{}
	hooks       []func(interface{}) interface{}
	history     []TyperScannerFuncCall
	mutex       sync.Mutex
}

// Scanner delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockTyper) Scanner(v0 interface{}) interface{} {
	r0 := m.ScannerFunc.nextHook()(v0)
	m.ScannerFunc.appendCall(TyperScannerFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the Scanner method of
// the parent MockTyper instance is invoked and the hook queue is empty.
func (f *TyperScannerFunc) SetDefaultHook(hook func(interface{}) interface{}) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Scanner method of the parent MockTyper instance invokes the hook at the
// front of the queue and discards it. After the queue is empty, the default
// hook function is invoked for any future action.
func (f *TyperScannerFunc) PushHook(hook func(interface{}) interface{}) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *TyperScannerFunc) SetDefaultReturn(r0 interface{}) {
	f.SetDefaultHook(func(interface{}) interface{} {
		return r0
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *TyperScannerFunc) PushReturn(r0 interface{}) {
	f.PushHook(func(interface{}) interface{} {
		return r0
	})
}

func (f *TyperScannerFunc) nextHook() func(interface{}) interface{} {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *TyperScannerFunc) appendCall(r0 TyperScannerFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of TyperScannerFuncCall objects describing the
// invocations of this function.
func (f *TyperScannerFunc) History() []TyperScannerFuncCall {
	f.mutex.Lock()
	history := make([]TyperScannerFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// TyperScannerFuncCall is an object that describes an invocation of method
// Scanner on an instance of MockTyper.
type TyperScannerFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 interface{}
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 interface{}
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c TyperScannerFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c TyperScannerFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// TyperValuerFunc describes the behavior when the Valuer method of the
// parent MockTyper instance is invoked.
type TyperValuerFunc struct {
	defaultHook func(interface{}) interface{}
	hooks       []func(interface{}) interface{}
	history     []TyperValuerFuncCall
	mutex       sync.Mutex
}

// Valuer delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockTyper) Valuer(v0 interface{}) interface{} {
	r0 := m.ValuerFunc.nextHook()(v0)
	m.ValuerFunc.appendCall(TyperValuerFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the Valuer method of the
// parent MockTyper instance is invoked and the hook queue is empty.
func (f *TyperValuerFunc) SetDefaultHook(hook func(interface{}) interface{}) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Valuer method of the parent MockTyper instance invokes the hook at the
// front of the queue and discards it. After the queue is empty, the default
// hook function is invoked for any future action.
func (f *TyperValuerFunc) PushHook(hook func(interface{}) interface{}) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *TyperValuerFunc) SetDefaultReturn(r0 interface{}) {
	f.SetDefaultHook(func(interface{}) interface{} {
		return r0
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *TyperValuerFunc) PushReturn(r0 interface{}) {
	f.PushHook(func(interface{}) interface{} {
		return r0
	})
}

func (f *TyperValuerFunc) nextHook() func(interface{}) interface{} {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *TyperValuerFunc) appendCall(r0 TyperValuerFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of TyperValuerFuncCall objects describing the
// invocations of this function.
func (f *TyperValuerFunc) History() []TyperValuerFuncCall {
	f.mutex.Lock()
	history := make([]TyperValuerFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// TyperValuerFuncCall is an object that describes an invocation of method
// Valuer on an instance of MockTyper.
type TyperValuerFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 interface{}
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 interface{}
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c TyperValuerFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c TyperValuerFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}
